ecommerce/urls.py

from django.urls import path, include
from . import views

from django.views.generic import TemplateView

urlpatterns = [
    path('', views.home, name="home"),
    path('signup/', views.signup, name='signup'),
    path('signout/', views.signout, name='logout'),
    path('signin/', views.signin, name='signin'),
    path('addStock/', views.addStock, name='addStock'),
    path('buy', views.buy, name="buy"),
    path('buy/<str:prod>/delete', views.delete_prod, name='delete_prod'),
    path('cart/', views.cart, name="cart"),
    path('cart/delete_all', views.delete_all, name="delete_all"),
    path('cart/<str:prod>', views.addCart, name="addCart"),
    path('cart/delete/<str:prod>', views.deleteFromCart, name="deleteFromCart"),
    path('cart/update/<str:prod>', views.update_stock, name="update_stock"),
    path('contacto/', views.contacto, name="contacto"),
    path('aboutus/', views.aboutus, name="aboutus"),
    path('product/<int:id>', views.product_detail, name="product_detail"),
    path('paypal/', views.paypal, name="paypal"),
    path('preCompra/', views.preCompra, name="preCompra"),
    path('datos/', views.verPedidos, name="verPedidos"),
    path('datos/delete/<int:pedido>', views.eliminarPedido, name="eliminarPedido"),
    path('filtrar/<int:cat>', views.filtrar, name="filtrar"),
    # path('pago/', views.pago, name="pago")

]


proyecto/urls.py
from django.contrib import admin
from django.urls import path, include
from ecommerce import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('ecommerce.urls')),
    path('accounts/', include('allauth.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ecommerce/models.py

from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class categorias(models.Model):
    nombre_cat = models.CharField(max_length=50)
    activo = models.BooleanField(default=True)
    def __str__(self) -> str:
            return self.nombre_cat

def marketplace_directory_path():
    return 'productos'

class stockProducts(models.Model):
    thumbnail = models.ImageField(null=True, upload_to=marketplace_directory_path())
    nom_prod = models.CharField(max_length=50)   
    precio_prod = models.FloatField()   
    descripcion = models.TextField(max_length=250)
    categoria = models.ForeignKey(categorias, on_delete=models.CASCADE)
    hayStock = models.BooleanField(default=True)

    def __str__(self) -> str:
        return self.nom_prod

class carrito(models.Model):
    foto = models.ImageField(null=True)
    nom_prod = models.TextField(max_length=200)
    cant_prod = models.IntegerField()
    precio_prod = models.FloatField()
    prod = models.ForeignKey(stockProducts, null=True, on_delete=models.CASCADE)
    user = models.ForeignKey(User, null=True, on_delete=models.CASCADE)
    def __str__(self) -> str:
        return self.nom_prod


class pedidos(models.Model):
    nombre = models.TextField()
    DNI = models.IntegerField()
    telefono = models.IntegerField()
    total = models.FloatField()



# class Compra(models.Model):
#     id = models.CharField(primary_key= True, max_length=100)
#     estado = models.CharField(max_length=100, null=True)
#     codigo_estado = models.CharField(max_length=100, null=True)
#     # producto = models.ForeignKey(to=carrito, on_delete= models.SET_NULL, null = True),
#     total_de_la_compra= models.DecimalField(max_digits=5 ,decimal_places=2, null=True)
#     nombre_cliente = models.CharField(max_length=100, null=True)
#     apellido_cliente=models.CharField(max_length=100, null=True)
#     correo_cliente = models.EmailField(max_length=100, null=True)
#     direccion_cliente = models.CharField(max_length=100, null=True)
#     def _str_(self):
#         return self.nombre_cliente

ecommerce/forms.py
from django import forms
from django.forms import ModelForm
from .models import stockProducts
class stockForm(ModelForm):
    class Meta:
        model = stockProducts
        fields = ['thumbnail', 'nom_prod', 'precio_prod', 'descripcion', 'categoria']

class FormularioContacto(forms.Form):
    asunto=forms.CharField(max_length=70)
    mensaje=forms.CharField(max_length=500)
    email=forms.EmailField()

class preCompra(forms.Form):
    DNI = forms.IntegerField()
    nombre = forms.CharField(max_length=60)
    apellido = forms.CharField(max_length=60)
    telefono = forms.IntegerField()
    

ecommerce/views.py
import re
from unittest import result
from django.core.mail import send_mail
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth import login, logout, authenticate
from django.contrib.auth.decorators import login_required
from django.contrib.admin.views.decorators import staff_member_required
from django.http import JsonResponse
from .models import stockProducts, carrito, pedidos, categorias
from . import forms
from ecommerce import models
import operator

from paypalcheckoutsdk.core import PayPalHttpClient, SandboxEnvironment
from paypalcheckoutsdk.orders import OrdersGetRequest, OrdersCaptureRequest
import sys
import json


def paypal(request):
    total = 0
    prods = carrito.objects.all().filter(user=request.user)
    for prod in prods:
        total += prod.precio_prod
    if request.method == "POST":
        pedidos.objects.create(nombre=request.POST['nombre'] + request.POST['apellido'],
                               DNI=request.POST['DNI'], telefono=request.POST['telefono'], total=total)
    return render(request, 'paypal.html', {
        'total': total
    })


# def pago(request):
#     data = json.loads(request.body)
#     order_id = data['orderID']
#     detalle = GetOrder().get_order(order_id)
#     detalle_precio = float (detalle.result.purchase_units[0].amount.value)
#     print(detalle_precio)

#     trx = CaptureOrder().capture_order(order_id, debug=True)
#     pedido = models.Compra(
#         id= trx.result.id,
#         estado= trx.result.status,
#         codigo_estado= trx.status_code,
#         nombre_cliente= trx.result.payer.name.given_name,
#         apellido_cliente= trx.result.payer.name.surname,
#         correo_cliente= trx.result.payer.email_address,
#         direccion_cliente= trx.result.purchase_units[0].shipping.address.address_line_1)
#     pedido.save()
#     data = {
#         "id": f"{trx.result.id}",
#         "nombre_cliente": f"{trx.result.payer.name.given_name}"
#     }
#     return JsonResponse(data)


# class PayPalClient:
#     def __init__(self):
#         self.client_id = "AZEr3NvMIdU0MhJt9Y0GNfb6BTP4FJyCWg6uOrV_QC9SK2QrgZMndjjdVknM-lfA5-J9LeRP4pKvhaCb"
#         self.client_secret = "EJDECmbo4dasEyT4pj2ZwKrFhox1W_PlZ1AI8cQstgi9TkD9KHzUhppOvtS0mOJFOH3y5FLy8QRLd4vA"
#         self.environment = SandboxEnvironment(client_id=self.client_id, client_secret=self.client_secret)
#         self.client = PayPalHttpClient(self.environment)
#     def object_to_json(self, json_data):
#         result = {}
#         if sys.version_info[0] < 3:
#             itr = json_data.__dict__.iteritems()
#         else:
#             itr = json_data.__dict__.items()
#         for key,value in itr:
#             if key.startswith("__"):
#                 continue
#             result[key] = self.array_to_json_arrray(value) if isinstance(value, list) else\
#                         self.object_to_json(value) if not self.is_primittive(value) else\
#                             value
#         return result

#     def array_to_json_array(self, json_array):
#         result=[]
#         if isinstance(json_array, list):
#             for item in json_array:
#                 result.append(self.object_to_json(item) if not self.is_primittive(item) \
#                                 else self.array_to_json_array(item) if isinstance(item, list) else item)
#         return result

#     def is_primittive(self, data):
#         return isinstance(data, str) or isinstance(data, unicode) or isinstance(data, int)

# class GetOrder(PayPalClient):
#   def get_order(self, order_id):
#     request = OrdersGetRequest(order_id)
#     response = self.client.execute(request)
#     print('Status Code: ', response.status_code)
#     print('Status: ', response.result.status)
#     print ('Order ID: ', response. result.id)
#     print ('Intent: ', response. result. intent)
#     print ('Links:')
#     for link in response.result.links:
#         print('\t{}: {}\tCall Type: {}'.format(link.rel, link.href, link.method))
#         print('Gross Amount: {} {}'.format(response.result.purchase_units[0].amount.currency_code,response.result.purchase_units[0].amount.value))


# class CaptureOrder (PayPalClient):
#    def capture_order(self, order_id, debug=False):
#      request = OrdersCaptureRequest(order_id)
#      response = self.client.execute(request)
#      if debug:
#        print('Status Code: ', response.status_code)
#        print('Status: ', response.result.status)
#        print('Order ID: ', response.result.id)
#        print('Links: ')
#        for link in response.result.links:
#             print('\t{}: {}\tCall Type: {}'.format(link.href, link.method))
#        print('Capture Ids: ')
#        for purchase_unit in response.result.purchase_units:
#             for capture in purchase_unit.payments.captures:
#                 print('\t', capture.id)
#             print("Buyer:")
#             print ("\tEmail Address: {}\n\tName: {}\n\tPhone Number: {}".format(response.result.payer.email_address,
#                 response.result.payer.name.given_name + " " + response.result.payer.name.surname,
#                 response.result.payer.phone.phone_number.national_number))
#             return response


def home(request):
    return render(request, 'home.html')


def aboutus(request):
    return render(request, 'aboutus.html')


def signup(request):
    if request.method == 'GET':
        return render(request, 'signup.html', {
            'form': UserCreationForm
        })
    else:
        if request.POST['password1'] == request.POST['password2']:
            try:
                user = User.objects.create_user(
                    username=request.POST['username'], password=request.POST['password1'])
                # print(user)
                user.save()
                # print("HASTA ACA LLEGAJAJAJ")
                # login(request, user)
                return redirect('/signin/')
            except:

                return render(request, 'signup.html', {
                    'form': UserCreationForm,
                    'error': 'Usuario existente'
                })
        else:
            return render(request, 'signup.html', {
                'form': UserCreationForm,
                'error': 'Las contraseñas no coinciden'
            })


@login_required
def signout(request):
    logout(request)
    return redirect('/')


def signin(request):
    if request.method == 'GET':

        return render(request, 'signin.html', {
            'form': AuthenticationForm
        })
    else:
        user = authenticate(
            request, username=request.POST['username'], password=request.POST['password'])
        if user is None:

            return render(request, 'signin.html', {
                'form': AuthenticationForm,
                'error': "El usuario o contraseña es incorrecto"
            })
        else:
            login(request, user)
            return redirect('/buy')


@login_required
def addStock(request):

    if request.method == 'GET':
        return render(request, 'addProduct.html', {
            'form': forms.stockForm
        })
    else:
        print(request.POST)
        print(models.categorias.objects.get(id=request.POST['categoria']))

        stockProducts.objects.create(thumbnail=request.FILES['thumbnail'], nom_prod=request.POST['nom_prod'], precio_prod=request.POST['precio_prod'], descripcion=request.POST['descripcion'],
                                     categoria=models.categorias.objects.get(id=request.POST['categoria']))

        return redirect('buy')


@login_required
def buy(request):
    busqueda = request.GET.get("buscar")

    stock = stockProducts.objects.all()
    categoria = categorias.objects.all()

    if busqueda:
        stock = stockProducts.objects.filter(
            nom_prod__icontains=busqueda
        )

    return render(request, 'buy.html', {
        'products': stock,
        'categorias': categoria
    })


@login_required
@staff_member_required
def delete_prod(request, prod):

    product = get_object_or_404(stockProducts, nom_prod=prod)
    if request.method == 'POST':

        product.delete()
        return redirect('buy')


@login_required
def addCart(request, prod):
    ArrayProductos = []
    cantidad = request.GET.get("cant")

    product = get_object_or_404(stockProducts, nom_prod=prod)
    products = carrito.objects.all().filter(user=request.user)

    for i in products:
        ArrayProductos.append(i.nom_prod)

    if cantidad:
        if product.nom_prod in ArrayProductos:
            p = carrito.objects.filter(user=request.user).get(nom_prod=prod)
            p.cant_prod += int(cantidad)
            p.precio_prod += p.precio_prod*int(cantidad)
            p.save()
        else:
            carrito.objects.create(foto=product.thumbnail, nom_prod=product.nom_prod, cant_prod=int(
                cantidad), precio_prod=product.precio_prod*int(cantidad), prod=product, user=request.user)

    else:
        return render(request, "product_detail.html", {
            'data': product,
            'error': 'No se eligio una cantidad'
        })

    return redirect('cart')


def contacto(request):

    if request.method == "POST":

        miFormulario = forms.FormularioContacto(request.POST)

        if miFormulario.is_valid():
            inForm = miFormulario.cleaned_data
            print(inForm)
            send_mail(inForm['asunto'], inForm['mensaje'], inForm.get(
                'email', ''), ['davidarechagaippolito@gmail.com'],)

            return render(request, "formulario_contacto.html")
    else:

ecommerce/templates/aboutus.html
{% extends 'base.html' %} {% load static %}

<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>About Us</title>
  </head>
  <body>
    
    {% block content %}
    <link rel="stylesheet" href="{% static 'aboutus.css' %}" />
    
    <main class="main-aboutus">
      <div class="content">
        <h1>About Us</h1>
        <img src="{% static 'aboutus.svg' %}" alt="" />
        <p>
          Somos un grupo de 3 estudiantes de la E.T. 36 D.E. 15 y esta página es
          nuestro proyecto informatico de 5to año. Elegimos hacer este ecommerce
          para poder ayudar a la mama de los integrantes con su venta de bolsos.
        </p>
      </div>
    </main>

    
    {% endblock content %}
  </body>
</html>

ecommerce/templates/addProduct.html
{% extends 'base.html' %} {% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="stylesheet" href="addProduct.css" />
    <script src="https://code.jquery.com/jquery-3.6.1.min.js"></script>
    <title>Document</title>
  </head>
  <body>
    {% block content %}
    <link rel="stylesheet" href="{% static 'addProduct.css' %}" />
    <main class="main-addProduct">
      <form
        action=""
        method="POST"
        enctype="multipart/form-data"
        class="form-addProduct"
      >
        {% csrf_token %}
        <h1>Agregar producto</h1>
        

        <label for="id_thumbnail">Seleccione una imagen</label>

        <input
          type="file"
          name="thumbnail"
          accept="image/*"
          required=""
          id="id_thumbnail"
          class="img"
        />

        <div class="input-div">
          <input
            type="text"
            name="nom_prod"
            maxlength="50"
            required=""
            id="id_nom_prod"
            autocomplete="off"
          />
          <label for="id_nom_prod">Nombre</label>
        </div>

        <div class="input-div">
          <input
            type="number"
            name="precio_prod"
            step="any"
            required=""
            id="id_precio_prod"
          />
          <label for="id_precio_prod">Precio</label>
        </div>

        <div class="input-div input-div-textarea">
          <textarea
            name="descripcion"
            cols="40"
            rows="10"
            maxlength="250"
            required=""
            id="id_descripcion"
          ></textarea>
          <label for="id_descripcion">Descripcion</label>
        </div>

        <!-- <label for="id_categoria">Categoria:</label> -->

        <select name="categoria" required="" id="id_categoria">
          <option value="" selected="">CATEGORIA</option>

          <option value="1">bolsos</option>

          <option value="2">carteras</option>

          <option value="3">mochilas</option>

          <option value="4">riñonera</option>
        </select>

        <button>Agregar</button>
      </form>
    </main>

    <script>
      let lista = $(".input-div");
      for (const e of lista) {
        let children = e.children;
        let input = children[0];
        let label = children[1];
        $(input).on("focus", () => {
          $(label).addClass("focussed");
          console.log("3ehuqweghiwq");
        });
        $(input).on("blur", () => {
          if (!$.trim($(input).val())) {
            $(label).removeClass("focussed");
          }
        });
      }
    </script>
    {% endblock %}
  </body>
</html>

ecommerce/templates/addToCart.html
{% extends 'base.html' %} {% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Document</title>
  </head>
  <body>
    {% block content %}
    <link rel="stylesheet" href="{% static 'addToCart.css' %}" />
    <main class="main-cart">
      {% if total != 0%}
      <div class="products">
        {% for prod in prods %}
        <div class="product">
          <img src="{{prod.foto.url}}" alt="bolso" class="product-img" />
          <p class="product-name">{{prod.nom_prod}}</p>
          <p class="product-cant">Cantidad: {{prod.cant_prod}}</p>
          <form
            action="{% url 'deleteFromCart' prod.nom_prod %}"
            method="POST"
            class="deleteproduct"
          >
            {% csrf_token %}
            <button>Borrar</button>
          </form>
        </div>
        {% endfor %}
      </div>
      <div class="details">
        <p class="totalvalue">Total: <span>${{total}}</span></p>
        <form action="{% url 'delete_all' %}" method="POST" class="emptycart">
          {% csrf_token %}
          <button
            style="
              display: flex;
              gap: 5px;
              height: 40px;
              display: flex;
              align-items: center;
              justify-content: center;
            "
          >
            <img src="{% static 'delete.svg' %}" alt="" style="height: 20px" />
            Vaciar carrito
          </button>
        </form>
        <form action="{% url 'preCompra' %}" class="buy">
          <button
            style="
              display: flex;
              gap: 5px;
              height: 40px;
              display: flex;
              align-items: center;
              justify-content: center;
            "
          >
          <img src="{% static 'cart.svg' %}" alt="" style="height: 30px">
            Ir a comprar
          </button>
        </form>
      </div>
      {% else %}
      <h1>EL CARRITO ESTA VACIO</h1>
      {% endif %}
    </main>

    {% endblock content %}
  </body>
</html>

ecommerce/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="es">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="stylesheet" href="{% static 'base.css' %}" />
    <script src="https://code.jquery.com/jquery-3.6.1.min.js"></script>
    <title>Buy</title>
  </head>
  <body>
    <nav class="navbar">
      <div class="navbar__hamburguer">
        <input type="checkbox" id="hamburguerCheck" />
        <span class="hamburguer">☰</span>
        <ul class="navbar__dropdownMenu hide" id="dropdown">
          {% if user.is_staff %}
          <li class="rojo">
            <a href="{% url 'addStock' %}">Agregar producto</a>
          </li>
          <li class="rojo2">
            <a href="{% url 'verPedidos' %}">Ver pedidos</a>
          </li>
          {% endif %}

          <li class="naranja"><a href="{% url 'buy' %}">STOCK</a></li>
          <li class="amarillo"><a href="{% url 'cart' %}">CARRITO</a></li>

          {% if user.is_authenticated %}
          <li class="verde"><a href="{% url 'logout' %}">LOG OUT</a></li>
          {% else %}
          <li class="celeste"><a href="{% url 'signup' %}">SIGN UP</a></li>
          <li class="azul"><a href="{% url 'signin' %}">SIGN IN</a></li>
          {% endif %}

          <li class="violeta"><a href="{% url 'contacto' %}">CONTACT</a></li>
          <li class="rosa"><a href="{% url 'aboutus' %}">ABOUT US</a></li>
        </ul>
      </div>
      <a href="/" style="color: #000; text-decoration: none; user-select: none;"><h1 class="navbar__title">BAGUAL</h1></a>
    </nav>

    {% block content %}
    {% endblock %}


    <script>
      let status = true;

      $("#hamburguerCheck").on("change", () => {
        status = !status;
        if (status) {
          $("#dropdown").addClass("hide");
        } else {
          $("#dropdown").removeClass("hide");
        }
      });
    </script>
  </body>
</html>

ecommerce/templates/buy.html
{% extends 'base.html' %} {% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="stylesheet" href="{% static 'buy.css' %}" />
    <title>STOCK</title>
  </head>
  <body>
    {% block content %}
    <link rel="stylesheet" href="{% static 'buy.css' %}" />
    <main class="main-buy">
      <div class="main-filter-div">
        <ul class="main-filter-ul">
          <li>
            <span>Filtrar:</span>
          </li>
          {% for cat in categorias %}
          <li>
            <form action="{% url 'filtrar' cat.id %}" method="POST">
              {% csrf_token %}
              <a href="{% url 'filtrar' cat.id %}" style="text-transform: uppercase;">{{cat}}</a>
            </form>
          </li>
          {% endfor %}
        </ul>

      
      <form action="" method="GET" class="searchbar">

        <input type="search" name="buscar" id="buscar" autocomplete="off">
        <button><img src="{% static 'search.svg' %}" alt="" /></button>
      </form>
      
      <div class="products">
        {% for product in products %} 
        {% if product.hayStock %}

        <a href="{% url 'product_detail' product.id  %}" class="product_card">
          <img src="{{product.thumbnail.url}}" alt="" />
          <span class="product">{{product}}</span>
          <p style="color: green; font-size: 20px;">${{product.precio_prod}}</p>
        </a>

        {% else %} {% if user.is_staff %}
        <a href="{% url 'product_detail' product.id  %}" class="product_card">
          <img src="{{product.thumbnail.url}}" alt="" class="imagen_buy" />
          <span class="product">{{product}}</span>
          <p style="color: green; font-size: 20px;">${{product.precio_prod}}</p>
        </a>
        {% else %}
        <div class="product_card">
          <img src="{{product.thumbnail.url}}" alt=""  />
          <span class="product">{{product}}</span>
          <p style="color: green; font-size: 20px;">${{product.precio_prod}}</p>
          <p style="color: red;">NO HAY STOCK</p>
        </div>
        {% endif %} 
        {% endif %} 
        {% endfor %}

      </div>
    </main>

    {% endblock %}
  </body>
</html>

ecommerce/templates/formulario_contacto.html
{% extends 'base.html' %}
{% load static %}
<!DOCTYPE html>
<html lang="en">
  
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="stylesheet" href="{% static 'contacto.css' %}" />
    <script src="https://code.jquery.com/jquery-3.6.1.min.js"></script>
    <title>Contacto</title>
  </head>
  <body>
    
  {% block content %}
  <link rel="stylesheet" href="{% static 'contacto.css' %}" />
    
    <main class="main-contact">
        
        <form action="" method="POST" class="contact-form">
          {% csrf_token %}
          <h1 class="contact-title">Contacto</h1>
            <div class="input-div">
          <input type="text" name="asunto" id="asunto" autocomplete="off" />
          <label for="asunto">Asunto</label>
        </div>
        <div class="input-div">
          <input type="email" name="email" id="email" autocomplete="off" />
          <label for="email">Email</label>
        </div>
        <div class="input-div">
            <textarea name="mensaje" id="mensaje" cols="30" rows="10"> </textarea>
            <label for="mensaje">Mensaje</label>
        </div>

        <input type="submit" value="Enviar" />
      </form>
    </main>

    <script>
      let lista = $(".input-div");
      for (const e of lista) {
        let children = e.children;
        let input = children[0];
        let label = children[1];
        $(input).on("focus", () => {
          $(label).addClass("focussed");
        });
        $(input).on("blur", () => {
          if (!$.trim($(input).val())) {
            $(label).removeClass("focussed");
          }
        });
      }
    </script>
    
    {% endblock %}
  </body>

  
</html>

ecommerce/templates/home.html
{% load static %}
<!DOCTYPE html>
<html lang="es">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    
    <title>Bagual</title>
  </head>
  <body>
    
    <!-- {% block content %} -->

    
    <link rel="stylesheet" href="{% static 'home.css' %}">

    <main class="landing-main">
      <h1 style="user-select: none;">BAGUAL</h1>
      <a href="#grilla" style="user-select: none;">
        <img src="{% static 'arrowdown.svg' %}" alt="" />
      </a>
    </main>
    <div id="grilla" class="landing-grilla-menu">
      <div class="stock"><a href="{% url 'buy' %}">STOCK</a></div>
      <div class="aboutus"><a href="{% url 'aboutus' %}">ABOUT US</a></div>
      <div class="contact"><a href="{% url 'contacto' %}">CONTACT</a></div>
      {% if user.is_authenticated %}
      <div class="login"><a href="{% url 'logout' %}">LOG OUT</a></div>
      {% else %}
      <div class="login"><a href="{% url 'signin' %}">LOG IN</a></div>
      {% endif%}
      <div class="singup"><a href="{% url 'signup' %}">SIGN UP</a></div>
    </div>

    
    <!-- {% endblock %} -->
  </body>
</html>

ecommerce/templates/preCompra.html
{% extends 'base.html' %}
{% load static %}

<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Document</title>
  </head>
  <body>
    {% block content %}
    <script src="https://code.jquery.com/jquery-3.6.1.min.js"></script>
    <link rel="stylesheet" href="{% static 'preCompra.css' %}" />
    <main class="main-precompra">
      <form action="/paypal/" method="POST" class="form-precompra">
        {% csrf_token %}
        <h1>Datos</h1>

        <div class="input-div">
          <input
            type="text"
            name="nombre"
            maxlength="60"
            required=""
            id="id_nombre"
            autocomplete="off"
          />
          <label for="id_nombre">Nombre</label>
        </div>

        <div class="input-div">
          <input
            type="text"
            name="apellido"
            maxlength="60"
            required=""
            id="id_apellido"
            autocomplete="off"
          />
          <label for="id_apellido">Apellido</label>
        </div>
        <div class="input-div">
          <input type="number" name="DNI" required="" id="id_DNI" />
          <label for="id_DNI">Dni</label>
        </div>

        <div class="input-div">
          <input type="number" name="telefono" required="" id="id_telefono" />
          <label for="id_telefono">Telefono</label>
        </div>

        <button>Pagar</button>
      </form>
    </main>

    <script>
      let lista = $(".input-div");
      for (const e of lista) {
        let children = e.children;
        let input = children[0];
        let label = children[1];
        $(input).on("focus", () => {
          $(label).addClass("focussed");
        });
        $(input).on("blur", () => {
          if (!$.trim($(input).val())) {
            $(label).removeClass("focussed");
          }
        });
      }
    </script>

    {% endblock content %}
  </body>
</html>